<?xml version="1.0"?>
<package format="3">
  <name>obstacle_context</name>
  <version>0.0.1</version>
  <description>LaserScan preprocessing, obstacle clustering, odom-compensated tracking, and RViz markers</description>

  <maintainer email="kjh0212031@gmail.com">kjh</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>

  <depend>tf2</depend>

  <depend>obstacle_context_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>